python-app:
  name: python-app
  replicaCount: 1
  image:
    repository: adnan3594/python-app
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer

postgres:
  replicaCount: 1
  image:
    repository: postgres
    tag: "15"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5432
  persistence:
    size: 1Gi
    storageClass: "standard"